# Generated by Django 5.0.6 on 2024-05-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('links', models.TextField()),
            ],
        ),
    ]
