# Generated by Django 5.0.6 on 2024-05-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperesult',
            name='summary',
            field=models.TextField(default='No summary available'),
        ),
    ]
